Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |v|
    v.memory = 512
  end

  config.vm.box = "elastic/ubuntu-16.04-x86_64"

  config.vm.define "dbserver" do |db|
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
  end

  config.vm.define "appserver" do |app|
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
  end
end
